interface dummyType {
  img: string;
  title: string;
  subtitle: string;
  km: string;
}
interface latDummy {
  lat: number;
  lng: number;
}

export const AccDummy = [
  {
    img: '/homeicon.png',
    id: 1,
    title: '어떠한 펜션',
    subtitle: '산속, 탁트인 펜션!',
    address: '경기도 양평군 떙떙읍',
    call: '02-000-0000',
    content: '숯불 바베큐 가능, 인근 빠지 위치한 신식펜션!',
    km: '5km',
  },
  {
    img: '/homeicon.png',
    id: 2,
    title: '멋진 레지던스',
    subtitle: '도심 중심, 편리한 레지던스!',
    address: '서울시 강남구 벼룩동',
    call: '02-111-1111',
    content: '최신 시설을 갖춘 건물, 대중교통 접근성이 좋은 위치!',
    km: '3km',
  },
  {
    img: '/homeicon.png',
    id: 3,
    title: '평화로운 별장',
    subtitle: '숲 가운데, 아늑한 별장!',
    address: '강원도 원주시 구두리',
    call: '033-222-2222',
    content: '자연친화적인 디자인, 산림에서 힐링할 수 있는 공간!',
    km: '12km',
  },
  {
    img: '/homeicon.png',
    id: 4,
    title: '한강뷰 아파트',
    subtitle: '한강 전망, 고급 아파트!',
    address: '서울시 영등포구 서강동',
    call: '02-333-3333',
    content: '현대식 디자인, 한강 공원 인접한 위치!',
    km: '2km',
  },
  {
    img: '/homeicon.png',
    id: 5,
    title: '캠핑 가든',
    subtitle: '휴식과 캠핑의 만남!',
    address: '충청북도 청주시 응봉공원',
    call: '043-444-4444',
    content: '텐트와 캠핑용품 대여, 가족 친화적인 시설!',
    km: '8km',
  },
  {
    img: '/homeicon.png',
    id: 6,
    title: '해변 빌라',
    subtitle: '해수욕장 근처, 아름다운 빌라!',
    address: '부산시 해운대구 용광리',
    call: '051-555-5555',
    content: '해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!',
    km: '1km',
  },
  {
    img: '/homeicon.png',
    id: 6,
    title: '해변 빌라',
    subtitle: '해수욕장 근처, 아름다운 빌라!',
    address: '부산시 해운대구 용광리',
    call: '051-555-5555',
    content: '해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!',
    km: '1km',
  },
  {
    img: '/homeicon.png',
    id: 6,
    title: '해변 빌라',
    subtitle: '해수욕장 근처, 아름다운 빌라!',
    address: '부산시 해운대구 용광리',
    call: '051-555-5555',
    content: '해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!',
    km: '1km',
  },
  {
    img: '/homeicon.png',
    id: 6,
    title: '해변 빌라',
    subtitle: '해수욕장 근처, 아름다운 빌라!',
    address: '부산시 해운대구 용광리',
    call: '051-555-5555',
    content:
      '해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!해변에서 도보로 접근 가능, 수영장 및 수영장 옆 바!',
    km: '1km',
  },
];

export const tourDummy = [
  {
    img: '/homeicon.png',
    id: 1,
    title: '광화문',
    subtitle: '광장, 역사 유적',
    address: '서울 종로구 사직로 ',
    call: '02-000-0000',
    content: '한반도 일대 최고 규모의 광장으로, 조선 시대부터 국가의 중심 지역으로 사용되었으며, 2009년부터 광복 이후 정국을 대표하는 역사와 공간으로 규정되어 있다.',
    km: '5km',
  },
  {
    img: '/homeicon.png',
    id: 2,
    title: '롯데타워',
    subtitle: '빌딩, 쇼핑몰',
    address: '서울 송파구 올림픽로 300',
    call: '02-111-1111',
    content: 'lotte world tower',
    km: '10km',
  },
  {
    img: '/homeicon.png',
    id: 3,
    title: '서울대공원',
    subtitle: '유원지,동물원',
    address: '과천시 사직로 161',
    call: '02-222-2222',
    content:
      '1963년 1월 21일 사적으로 지정되었다. 역성혁 명(易姓 로 조선을 세운 이성계(李成桂)와 그 지지자들은 고려의 서울인 개경(開京)을 안전하게 지키기 위하여 팔각정(八角亭)을 비롯하여 시청(始政臺)·영조각(映照閣)·상효(上孝)·하효(下孝) 등의 요새와 건물을 짓게 되었다.',
    km: '1km',
  },
  {
    img: '/homeicon.png',
    id: 4,
    title: '청계천',
    subtitle: '상징적인 하천',
    address: '서울 중구 서애로',
    call: '02-333-3333',
    content: '필동, 충무로, 을지로, 쌍문, 노량진, 태릉, 종암, 옥수, 잠실 대표적인 지하철 역에서 하천을 따라 산책로가 이어져 있다. ',
    km: '3km',
  },
  {
    img: '/homeicon.png',
    id: 5,
    title: '남산타워',
    subtitle: '랜드마크, 전망대',
    address: '서울 용산구 남산공원길 105',
    call: '02-444-4444',
    content: '분위기 좋은 상점과 레스토랑들이 모여있는 남산타운과 재미있는 인터랙티브 체험을 ��� 수 있는 상상마당 등 다양한 볼거리와 체험이 가능한 랜드마크입니다.',
    km: '2km',
  },
  {
    img: '/homeicon.png',
    id: 4,
    title: '청계천',
    subtitle: '상징적인 하천',
    address: '서울 중구 서애로',
    call: '02-333-3333',
    content: '필동, 충무로, 을지로, 쌍문, 노량진, 태릉, 종암, 옥수, 잠실 대표적인 지하철 역에서 하천을 따라 산책로가 이어져 있다. ',
    km: '3km',
  },
  {
    img: '/homeicon.png',
    id: 5,
    title: '남산타워',
    subtitle: '랜드마크, 전망대',
    address: '서울 용산구 남산공원길 105',
    call: '02-444-4444',
    content: '분위기 좋은 상점과 레스토랑들이 모여있는 남산타운과 재미있는 인터랙티브 체험을 ��� 수 있는 상상마당 등 다양한 볼거리와 체험이 가능한 랜드마크입니다.',
    km: '2km',
  },
  {
    img: '/homeicon.png',
    id: 4,
    title: '청계천',
    subtitle: '상징적인 하천',
    address: '서울 중구 서애로',
    call: '02-333-3333',
    content: '필동, 충무로, 을지로, 쌍문, 노량진, 태릉, 종암, 옥수, 잠실 대표적인 지하철 역에서 하천을 따라 산책로가 이어져 있다. ',
    km: '3km',
  },
  {
    img: '/homeicon.png',
    id: 5,
    title: '남산타워',
    subtitle: '랜드마크, 전망대',
    address: '서울 용산구 남산공원길 105',
    call: '02-444-4444',
    content: '분위기 좋은 상점과 레스토랑들이 모여있는 남산타운과 재미있는 인터랙티브 체험을 ��� 수 있는 상상마당 등 다양한 볼거리와 체험이 가능한 랜드마크입니다.',
    km: '2km',
  },
];

export const latingDummy: latDummy[] = [
  { lat: 37.487347, lng: 126.9297416 },
  { lat: 37.4931458, lng: 126.926849 },
  { lat: 37.4931459, lng: 126.92685 },
  { lat: 37.493146, lng: 126.926852 },
];
