const regions = [
  { key: '서울', value: 11 },
  { key: '부산', value: 26 },
  { key: '대구', value: 27 },
  { key: '인천', value: 28 },
  { key: '광주', value: 29 },
  { key: '대전', value: 30 },
  { key: '울산', value: 31 },
  { key: '세종', value: 36 },
  { key: '경기', value: 41 },
  { key: '강원', value: 42 },
  { key: '충북', value: 43 },
  { key: '충남', value: 44 },
  { key: '전북', value: 45 },
  { key: '전남', value: 46 },
  { key: '경북', value: 47 },
  { key: '경남', value: 48 },
  { key: '제주', value: 50 },
];
export default regions;
